name: Coding Standart
on: [push]
permissions:
  contents: read
jobs:
    # Check there is no syntax errors in the project
    php-linter:
        name: PHP Syntax check 5.6|7.4|8.1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: PHP syntax checker 5.6
              uses: prestashop/github-action-php-lint/5.6@e4b49070638fc380f8057e7da93b1fc97a2e449d # v2.3.1
              with:
                folder-to-exclude: "! -path \"./.php_cs.dist.php\" ! -path \"./tests/*\" ! -path \"./vendor/*\""

            - name: PHP syntax checker 7.4
              uses: prestashop/github-action-php-lint/7.4@e4b49070638fc380f8057e7da93b1fc97a2e449d # v2.3.1
              with:
                folder-to-exclude: "! -path \"./.php_cs.dist.php\" ! -path \"./tests/*\"  ! -path \"./vendor/*\""

            - name: PHP syntax checker 8.1
              uses: prestashop/github-action-php-lint/8.1@e4b49070638fc380f8057e7da93b1fc97a2e449d # v2.3.1
              with:
                folder-to-exclude: "! -path \"./.php_cs.dist.php\" ! -path \"./tests/*\"  ! -path \"./vendor/*\""

    # Check the PHP code follow the coding standards
    php-cs-fixer-and-phpstan:
        name: PHP-CS-AND-PHPSTAN
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #v2.37.2
              with:
                php-version: '7.4'
                tools: composer:v2 php-cs-fixer phpstan

            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: vendor
                key: php-${{ hashFiles('composer.lock') }}

            - name: Install dependencies
              run: composer update --ignore-platform-reqs

            - name: Run PHP-CS-Fixer
              run: ./vendor/bin/php-cs-fixer fix src --dry-run --diff --using-cache=no

            - name: Static analysis of PHP code (PHPStan)
              run: ./vendor/bin/phpstan analyse -l max src