name: Coding Standart
on: [pull_request]
jobs:
    # Check there is no syntax errors in the project
    php-linter:
        name: PHP Syntax check 5.6|7.2|7.3
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.0.0

            - name: PHP syntax checker 5.6
              uses: prestashop/github-action-php-lint/5.6@master
              with:
                folder-to-exclude: "! -path \"./vendor/*\""

            - name: PHP syntax checker 7.2
              uses: prestashop/github-action-php-lint/7.2@master
              with:
                folder-to-exclude: "! -path \"./vendor/*\""

            - name: PHP syntax checker 7.3
              uses: prestashop/github-action-php-lint/7.3@master
              with:
                folder-to-exclude: "! -path \"./vendor/*\""

    # Check the PHP code follow the coding standards
    php-cs-fixer-and-phpstan:
        name: PHP-CS-AND-PHPSTAN
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                    php-version: '7.4'

            - name: Checkout
              uses: actions/checkout@v2.0.0

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: vendor
                key: php-${{ hashFiles('composer.lock') }}

            - name: Install dependencies
              run: composer update --ignore-platform-reqs

            - name: Run PHP-CS-Fixer
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no --diff-format udiff

            - name: Static analysis of PHP code (PHPStan)
              run: ./vendor/bin/phpstan analyse -l max src tests