name: Unit test
on: [push]
jobs:
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                    php-version: '8.1'

            - name: Checkout
              uses: actions/checkout@v2.0.0

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: vendor
                key: php-${{ hashFiles('composer.lock') }}

            - name: Install dependencies
              run: composer update --ignore-platform-reqs

            - name: Unit tests (PHPUnit)
              run: ./vendor/bin/phpunit .
